# crie uma lista de frutas e outra de vegetais. crie for loops para imprimir
# todas as combinações possíveis entre fruta e vegetal
# fruta primeiro e depois vegetal

'''frutas = ['banana', 'maça', 'melancia']
vegetais = [' cenoura', 'brocolis', 'alface']

for fruta in frutas:
    for vegetal in vegetais:
        print(fruta, '-', vegetal)
'''
# while loop

'''numero = 1
while numero <=10:
    print(numero)
    numero +=1
'''
# contador de termo repetido

'''clubes = ['spfc','sccp','sep','spfc','spfc','crf']
contador = 0
for clube in clubes:
    if clube == 'spfc':
        contador+=1
        print(clube)
'''
# if e else

'''numero = int(input('digite um número'))
if numero > 10:
    print('o número é maior que 10')
else:
    print('o número é igual ou menor que 10')
'''
